apiVersion: v1
kind: ConfigMap
metadata:
  name: monolith-config
  namespace: enterprise-prod
data:
  APP_ENVIRONMENT: "prod"
  JAVA_TOOL_OPTIONS: "-Xms512m -Xmx1024m"
  MICROSERVICE_URL: "http://microservice/microservice"
