apiVersion: apps/v1
kind: Deployment
metadata:
  name: monolith
  namespace: enterprise-prod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: monolith
  template:
    metadata:
      labels:
        app: monolith
    spec:
      containers:
        - name: monolith
          image: __MAIN_APP_IMAGE__
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: MICROSERVICE_URL
              value: http://microservice/microservice
            - name: JAVA_TOOL_OPTIONS
              value: -Xms512m -Xmx1024m
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: host
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: port
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: db
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: password
          readinessProbe:
            httpGet:
              path: /monolith/health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /monolith/health
              port: 8080
            initialDelaySeconds: 40
            periodSeconds: 10
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1024Mi
