server {
  listen 8080;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  location /monolith/ {
    proxy_pass ${MONOLITH_UPSTREAM};
  }

  location /microservice/ {
    proxy_pass ${MICROSERVICE_UPSTREAM};
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}