apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: enterprise-app
type: Opaque
stringData:
  DB_HOST: "__DB_HOST__"
  DB_PORT: "__DB_PORT__"
  DB_NAME: "__DB_NAME__"
  DB_USER: "__DB_USER__"
  DB_PASSWORD: "__DB_PASSWORD__"
  MYSQL_ROOT_PASSWORD: "__MYSQL_ROOT_PASSWORD__"
---
apiVersion: v1
kind: Secret
metadata:
  name: microservice-secrets
  namespace: enterprise-app
type: Opaque
stringData:
  DB_HOST: "__DB_HOST__"
  DB_PORT: "__DB_PORT__"
  DB_NAME: "__DB_NAME__"
  DB_USER: "__DB_USER__"
  DB_PASSWORD: "__DB_PASSWORD__"
---
apiVersion: v1
kind: Secret
metadata:
  name: monolith-secrets
  namespace: enterprise-app
type: Opaque
stringData:
  DB_HOST: "__DB_HOST__"
  DB_PORT: "__DB_PORT__"
  DB_NAME: "__DB_NAME__"
  DB_USER: "__DB_USER__"
  DB_PASSWORD: "__DB_PASSWORD__"
