apiVersion: v1
kind: Secret
metadata:
  name: microservice-secrets
  namespace: enterprise-perf-prod
type: Opaque
stringData:
  DB_HOST: "__DB_HOST__"
  DB_PORT: "__DB_PORT__"
  DB_NAME: "__DB_NAME__"
  DB_USER: "__DB_USER__"
  DB_PASSWORD: "__DB_PASSWORD__"
