nameOverride: microservice
fullnameOverride: microservice

replicaCount: 3

image:
  repository: registry.example.com/docker-local/microservice
  tag: replace-with-ci-build-number

resources:
  requests:
    cpu: 500m
    memory: 512Mi
  limits:
    cpu: 1000m
    memory: 1024Mi

config:
  env:
    APP_ENVIRONMENT: prod

secretProvider:
  enabled: true
  targetSecretName: microservice-secrets
  data:
    - secretKey: DB_HOST
      remoteRef:
        key: secret/data/prod/db
        property: db_host
    - secretKey: DB_PORT
      remoteRef:
        key: secret/data/prod/db
        property: db_port
    - secretKey: DB_NAME
      remoteRef:
        key: secret/data/prod/db
        property: db_name
    - secretKey: DB_USER
      remoteRef:
        key: secret/data/prod/db
        property: db_user
    - secretKey: DB_PASSWORD
      remoteRef:
        key: secret/data/prod/db
        property: db_password
