replicaCount: 3

image:
  repository: mechayan97/microservice
  tag: prod-stable

dbSecretName: db-secrets

resources:
  requests:
    cpu: 500m
    memory: 512Mi
  limits:
    cpu: 1000m
    memory: 1024Mi

env:
  APP_ENVIRONMENT: prod
