apiVersion: apps/v1
kind: Deployment
metadata:
  name: monolith
  namespace: enterprise-uat
spec:
  replicas: 2
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: monolith
  template:
    metadata:
      labels:
        app: monolith
    spec:
      imagePullSecrets:
        - name: jfrog-registry
      terminationGracePeriodSeconds: 30
      containers:
        - name: monolith
          image: __MAIN_APP_IMAGE__
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            runAsUser: 1000
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: monolith-config
            - secretRef:
                name: monolith-secrets
          readinessProbe:
            httpGet:
              path: /monolith/health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /monolith/health
              port: 8080
            initialDelaySeconds: 40
            periodSeconds: 10
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 750m
              memory: 1024Mi
