apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: microservice
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          env:
            - name: APP_ENVIRONMENT
              value: {{ .Values.env.APP_ENVIRONMENT | quote }}
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.dbSecretName | quote }}
                  key: host
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.dbSecretName | quote }}
                  key: port
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.dbSecretName | quote }}
                  key: db
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.dbSecretName | quote }}
                  key: user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.dbSecretName | quote }}
                  key: password
          readinessProbe:
            httpGet:
              path: /microservice/actuator/health/readiness
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /microservice/actuator/health/liveness
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
