{{- if .Values.secretProvider.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "microservice.fullname" . }}-external-secret
  labels:
    {{- include "microservice.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.secretProvider.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.secretProvider.secretStoreRef.name }}
    kind: {{ .Values.secretProvider.secretStoreRef.kind }}
  target:
    name: {{ include "microservice.secretName" . }}
    creationPolicy: Owner
  data:
    {{- range .Values.secretProvider.data }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        key: {{ .remoteRef.key }}
        property: {{ .remoteRef.property }}
    {{- end }}
{{- end }}
